name: CI/CD Pipeline for ASP.NET Web App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  # Continuous Integration Job
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore Deloitte_TVS_VAC.sln

      - name: clean the solution
        run: msbuild Deloitte_TVS_VAC.sln /t:Clean

      - name: Build the solution
        run: msbuild Deloitte_TVS_VAC.sln /p:Configuration=Release /p:Platform="Any CPU"


      #- name: Run Unit Tests
      #  run: dotnet test Deloitte_TVS_VAC.sln --logger "trx;LogFileName=TestResults.trx" --verbosity normal

  # Continuous Deployment Job with Manual Approval
  deploy:
    needs: build-and-test  # Runs only if CI job succeeds
    runs-on: windows-latest
    #environment: Production  # This is where manual approval is required
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Publish to folder
        run: msbuild Deloitte_TVS_VAC.sln /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="published"

               
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TVSUAT'
          slot-name: 'Production'
          package: ./
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_20E0088D26E7400A97FB47C9C1AF71E1 }}
